### PR TITLE
add mounting holes + plate with mounting

### PR DESCRIPTION
**Pull request by fauh45**
As there's already a development on v2, I'll make this PR and close #12. 

It does basically the same thing, this PR adds mounting hole (that maybe could be use for tenting, but I think it's better use a case for that). This PR will also add a new plate design, if there's a need to mount the plate to the PCB, as the design now allows for hotswap, so the switch doesn't wobble as bad.

Here's the preview of the new PCB.

Front View of the new PCB

Back View of the new PCB

There's also a new plate design that follows the new mounting hole.

image

### CODE REVIEW

**Comment by fauh45** [comment]
A little update on this,

It's not really that feasible to have the plate mount directly to the board. Except (maybe) if you find a 3-3.5mm 2mm standoff. I think a case would be a better way to mount it, so the mounting holes might need to be bigger, to allow for m2 standoff to pass through (usually 4mm+). This will allow the keyboard to be tray mounted.

**Comment by ggppjj** [comment]
This would also close #10.

**Comment by tompi** [comment]
Hey, sorry for not responding to this, but im still working on v2, have a prototype working, but want to do some more changes...

I find it very difficult to do pull requests on kicad projects, since there is just one big file, and you cant really work on a small part in isolation :(

If you would change the pull request to just include the plate/stl, I would happily merge it.

Otherwise I think I have to wait until v2 is done, and ask you to rebase on that....

**Comment by fauh45** [comment]
Oh hey @tompi, no totally, I understand. I don't think kicad was made to be version controlled. I'll update it to just include the plate!

Btw I've ordered some PCB with the mounting hole as well, I'll update how the fit and mounting solutions/tenting might work.

**Comment by fauh45** [comment]
@tompi hey there sorry to make you wait for a bit, I've merged the newest changes on PCB from v2 branch to mine. The only changes here should only be the plate.

**Comment by tompi** [comment]
Hey @fauh45 , this PR totally got lost... Really sorry.

Did you build it and did it work out ok?

As you might have seen, I decided to trim the outliune further,
so there really isnt place for mounting holes except for the inside...

Might have to drop the PR unless you are interested in making the plate for the v2.

**Comment by fauh45** [comment]
Heya @tompi sorry, I haven't really made it, though I've been using the keyboard barebone till now. I do have extra-work that I need to finished nowadays, not sure if I have the time to handle making a new plate for the v2...

**Comment by tompi** [comment]
Closing, since mounting holes are placed differently. Other plates and solutions are also available.

**Pull request closed without merging**
