### PR TITLE
Hotswap compatible + some improvements

### LINKED ISSUE #5: RJ45 socket is to far away from PCB edge
A bit inconvenient when trying to unplug cable...

### PR DESCRIPTION
**Pull request by fauh45**
Hey there @tompi,

I'm not sure if you take in contribution for your amazing cheapino project. As I see in the issue tabs there are some problems surrounding the V1 design, so I've taken an initiative to fix #5, #10, #3, and #2. I've tried to follow as close as I can to the trace style you've used. I've make sure to "melt" the traces, and also added teardrop to the connection.

As for the new stuff I've added,
- Reversible Hotswap
- Ethernet Jack is now further forward
- Some M2 mounting holes, the farthest one from the MCU should be able to use for tenting. Haven't checked though.

Here's the screenshot of the new PCB.
cheapino pcb front view

cheapino pcb back view

If there's improvement or any error in my design, please let me know. Thank you!

### CODE REVIEW

**Comment by tompi** [comment]
Hey, this looks great, but I already started v2 with lots of changes…(along
other stuff rearranging rj45 arrangement and smaller board outline…)

What size Are your mounting/tenting holes?
Im currently lesning towards m2 size(2.2mm) but open for suggestions if
there Are reasons to change…

**Comment by fauh45** [comment]
Ahh I see, I guess my version is a bit more towards intermediate step before v2 haha.

In my design I used M2 DIN/ISO sized hole, so yea 2.2mm. I feel like it's the most common size used in PCB, not sure why it should use M2.5 or bigger.

Anyhow, how do you achieve even smaller board outline with this layout? I feel like it's cramped already?

**Comment by fauh45** [comment]
And ups... Didn't see your V2 branch there...

**Comment by fauh45** [comment]
I'll close this PR, in favor of improvement of the V2 draft at #13

**Pull request closed without merging**
